# Generated by Django 2.2.3 on 2019-07-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_event', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_area', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('date_added', models.DateField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displays.EventType')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displays.Location')),
            ],
        ),
    ]
