# Generated by Django 2.2.3 on 2019-08-06 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0002_auto_20190719_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 2, 41, 25, 102219, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
