# Generated by Django 2.2.3 on 2019-09-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0004_auto_20190805_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type_of_event',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='party_area',
            field=models.CharField(max_length=20),
        ),
    ]
