# Generated by Django 2.2.3 on 2019-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0007_auto_20190914_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
